image: asciidoctor/docker-asciidoctor

build1:
    stage: build
    script:
        - cd ./bin/ && ./build-doc.sh
    artifacts:
        name: "compilation-pdf"
        paths:
            - build/
        expire_in: 2 week
