image: asciidoctor/docker-asciidoctor

pages:
    stage: build
    script:
        - cd ./bin/ && ./build-doc.sh "public"
    only:
        - master
    artifacts:
        name: "compilation-pdf"
        paths:
            - public/

build2:
    stage: build
    script:
        - cd ./bin/ && ./build-doc.sh "build"
    except:
        - master
    artifacts:
        name: "compilation-dev"
        paths:
            - build/
        expire_in: 2 days
    
