image: asciidoctor/docker-asciidoctor

build1:
    stage: build
    script:
        - cd ./bin/ && ./build-doc.sh public
    only:
        - master
    artifacts:
        name: "compilation-pdf"
        paths:
            - public/

build2:
    stage: test
    script:
        - cd ./bin/ && ./build-doc.sh build
    except:
        - master
    artifacts:
        name: "compilation-pdf"
        paths:
            - build/
        expire_in: 2 day
    