////
Les supports de Formatux sont publiés sous licence Creative Commons-BY-SA et sous licence Art Libre.
Vous êtes ainsi libre de copier, de diffuser et de transformer librement les œuvres dans le respect des droits de l’auteur.

    BY : Paternité. Vous devez citer le nom de l’auteur original.
    SA : Partage des Conditions Initiales à l’Identique.

Licence Creative Commons-BY-SA : https://creativecommons.org/licenses/by-sa/3.0/fr/
Licence Art Libre : http://artlibre.org/

Auteurs : Patrick Finet, Xavier Sauvignon, Antoine Le Morvan
////

[glossary]
== Glossaire

BASH::
    Bourne Again SHell
BIOS::
    Basic Input Output System
CIDR::
    Classless Inter-Domain Routing
Daemon::
    Disk And Execution MONitor
DHCP::
	Dynamic Host Control Protocol
DNS::
	Domain Name Service
FIFO::
	First In First Out
FQDN::
    Fully Qualified Domain Name
GNU::
    Gnu is Not Unix
HTTP::
    HyperText Transfer Protocol
ICP::
    Internet Cache Protocol
IFS::
    Internal Field Separator
LAN::
    Local Area Network
LDIF::
    LDAP Data Interchange Format
NTP::
    Network Time Protocol
nsswitch::
    Name Service Switch
OTP::
    One Time Password
POSIX::
    Portable Operating System Interface
POST::
    Power On Self Test
RDBMS::
    Relational DataBase Managed System
SGBD-R::
    Systèmes de Gestion de Base de Données Relationnelles
SHELL::
    En français "coquille". Á traduire par "interface système".
SMB::
    Server Message Block
SMTP::
    Simple Mail Tranfer Protocol
SSH::
    Secure SHell
SSL::
    Secure Socket Layer
TLS::
    Transport Layer Security, un protocole de cryptographie pour sécuriser les communications IP.
TTL::
    Time To Live
TTY::
    teletypewriter, qui se traduit téléscripteur. C'est la console physique.
UEFI::
    Unified Extensible Firmware Interface